version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: db_ai_cli_agent
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: db_ai_cli_agent